import Head from 'next/head';
import Header from './Header';
export default function Page({ children }) {
  return (
    <>
      <Head>
        <title>Above & Beyond Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </>
  );
}
